### ISSUE TITLE
Shorten url when user wants to share it 🤲

### ISSUE THREAD

**Issue by midudev** [midudev/codi.link#7]
Use some kind of url shorten in order to save the editor state on the url but short.

**Comment by B2-krunalrana** [comment]
also if we share some URL and that person make some changes in code block that time no one else get updated code / this URL not able to convert in qr code because it easily cross 250 char limit . 

we can use Django or any other frameworks to mange this rout dynamically 

or we can make similar platform like this : 
https://codeshare.io/
